default: &default
  host: localhost
  port: 5001
  adapter: postgresql
  encoding: UTF8
  username: ruby
  timeout: 5000
  reaping_frequency: 30

  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ruby_app
  password: postgres

test:
  <<: *default
  database: ruby_app_test
  password: postgres

production:
  <<: *default
  database: ruby_app_prod
  password: <%= ENV['EXERCISE_DATABASE_PASSWORD'] %>
